# Generated by Django 3.1.7 on 2021-03-22 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('create_date', models.DateField(null=True, verbose_name='Create date')),
                ('private', models.BooleanField(default=False, verbose_name='Is private')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Login')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='First name')),
                ('second_name', models.CharField(default='', max_length=100, verbose_name='Second_name')),
                ('status', models.TextField(max_length=100, verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Last login')),
            ],
            options={
                'verbose_name': 'Our user',
                'verbose_name_plural': 'Our user',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Text')),
                ('send_date', models.DateTimeField(null=True, verbose_name='Send date')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_chat', to='new_messenger.chat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_user', to='new_messenger.chatuser')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='ChatUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_users_chat', to='new_messenger.chat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_users_user', to='new_messenger.chatuser')),
            ],
            options={
                'verbose_name': 'Chat users',
                'verbose_name_plural': 'Chat users',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_admin', to='new_messenger.chatuser'),
        ),
        migrations.AddConstraint(
            model_name='chatusers',
            constraint=models.UniqueConstraint(fields=('user', 'chat'), name='chat_user constraint'),
        ),
    ]
